# Generated by Django 4.2.3 on 2023-07-06 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('owner_id', models.IntegerField()),
                ('thumb_url', models.URLField()),
                ('cover_url', models.URLField()),
                ('description', models.TextField()),
                ('last_activity', models.DateTimeField()),
                ('total_score', models.IntegerField()),
                ('total_tasks', models.IntegerField()),
                ('unchangeable', models.BooleanField()),
                ('include_weekly_report', models.BooleanField()),
                ('content_type', models.IntegerField()),
                ('is_netology', models.BooleanField()),
                ('bg_url', models.URLField()),
                ('video_url', models.URLField()),
                ('demo', models.BooleanField()),
                ('custom_author_names', models.CharField(max_length=64)),
                ('custom_contents_link', models.URLField()),
                ('hide_viewer_navigation', models.BooleanField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('group_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SimpleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('external_id', models.CharField(max_length=32)),
                ('role_id', models.IntegerField()),
                ('auth_type', models.IntegerField()),
                ('last_activity_at', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('lang', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('infinitely', models.BooleanField()),
                ('access_type', models.CharField()),
                ('finished', models.BooleanField()),
                ('apply_url', models.URLField()),
                ('deadline_soon', models.BooleanField()),
                ('assignments_count', models.IntegerField()),
                ('deadline_type', models.IntegerField()),
                ('slug', models.CharField(max_length=256)),
                ('period', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.course')),
                ('labels', models.ManyToManyField(to='v1.label')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='authors',
            field=models.ManyToManyField(to='v1.simpleuser'),
        ),
        migrations.AddField(
            model_name='course',
            name='types',
            field=models.ManyToManyField(to='v1.coursetype'),
        ),
    ]
