# Generated by Django 4.2.3 on 2023-07-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_alter_course_authors_alter_course_bg_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='authors',
            field=models.ManyToManyField(to='v1.simpleuser'),
        ),
        migrations.AlterField(
            model_name='course',
            name='types',
            field=models.ManyToManyField(to='v1.coursetype'),
        ),
    ]
