# Generated by Django 4.2.3 on 2023-07-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_simpleuser_locked_alter_simpleuser_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesession',
            name='apply_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='deadline_soon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='deadline_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='infinitely',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
